### ISSUE TITLE
[design test for pptalent]

### ISSUE THREAD

**Issue by fraserxu** [Wiredcraft/designer-test#1]
##### Target: 

Build the landing page for Shenzhen JavaScript conference

##### Requirement:

* Use Github to manage code with best practices(.gitignore, properly commit message...)
* Basic HTML + CSS(or SASS) to build a static conference page, need **mobile friendly** as we need the page to work well in wechat browser
* Page transition and animation([scrollmagic.js](http://janpaepke.github.io/ScrollMagic/)...)
* Parallax effect http://matthew.wagerfield.com/parallax/ 
* Have some build tool(Makefile, npm, gulp...) to build the code

You may add more sections to the page if you think there's not enough content(like speakers, schedule, social account...)

If you have any question, please let me know.

![shenjs-website-draft](https://cloud.githubusercontent.com/assets/195066/6054629/dc919b4c-ad2a-11e4-9c64-5d6dbea0cc56.png)

**Comment by pptalent** [comment]
Hi @fraserxu ,
You can now review my code , I just finish the basic requirements that you mentioned and make some test in different devices and browsers .
The rest of the work have been listed in the readme , but I think it's better to inform you first so that I can get feedback in time.

**Comment by pptalent** [comment]
Hi @fraserxu ,
You can check my work now

**Comment by fraserxu** [comment]
Ok, Thanks @pptalent .

Sorry for the later response because I was on the spring festival and do not have access to internet. 

I'll check your code and give you feedback as soon as possible.

**Comment by pptalent** [comment]
@fraserxu thank you : )
